# Generated by Django 5.0.3 on 2024-03-31 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='short_description',
        ),
        migrations.AddField(
            model_name='team',
            name='who_need',
            field=models.JSONField(default=[], verbose_name='Краткое описание'),
        ),
    ]
