# Generated by Django 4.2.11 on 2024-03-31 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0002_remove_team_short_description_team_who_need'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('name',)},
        ),
        migrations.CreateModel(
            name='TeamInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sent', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('invitation_type', models.CharField(choices=[('invite', 'Приглашение'), ('apply', 'Заявка')], default='invite', max_length=6, verbose_name='Тип')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('accepted', 'Принято'), ('declined', 'Отклонено')], default='pending', max_length=8, verbose_name='Статус')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_sent', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='teams.team', verbose_name='Команда')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_received', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
            ],
            options={
                'unique_together': {('from_user', 'to_user', 'team', 'invitation_type')},
            },
        ),
    ]
