# Generated by Django 5.0.3 on 2024-04-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_team_unique_together_teaminvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='who_need',
            field=models.JSONField(default=[], verbose_name='Кто нужен'),
        ),
    ]
