# Generated by Django 5.0.3 on 2024-04-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_limitation_main_message'),
        ('teams', '0004_alter_team_who_need'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='who_need',
        ),
        migrations.AddField(
            model_name='team',
            name='who_need',
            field=models.ManyToManyField(to='admin_panel.track', verbose_name='Кто нужен'),
        ),
    ]
