# Generated by Django 5.0.3 on 2024-04-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_remove_team_who_need_team_who_need'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminvitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('accepted', 'Принято'), ('declined', 'Отклонено'), ('closed', 'Закрыто')], default='pending', max_length=8, verbose_name='Статус'),
        ),
    ]
