# Generated by Django 5.0.3 on 2024-03-31 13:10

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_stack'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitation',
            name='main_message',
            field=tinymce.models.HTMLField(default='<h1>Hello world</h1>', verbose_name='Сообщение на главном экране'),
        ),
    ]
