# Generated by Django 5.0.3 on 2024-03-30 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=200, verbose_name='ФИО')),
                ('bio', models.TextField(verbose_name='О себе')),
                ('interests', models.JSONField(verbose_name='Интересы')),
                ('telegram_handle', models.CharField(max_length=255, verbose_name='Ник телеграм')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('track', models.CharField(max_length=255, verbose_name='Трек')),
                ('stack', models.JSONField(verbose_name='Стек')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('avatar', models.ImageField(upload_to='avatars/', verbose_name='Аватар')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
