# Generated by Django 5.0.3 on 2024-03-30 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_alter_profile_bio_alter_profile_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatar.png', upload_to='avatars/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.JSONField(blank=True, default=[], null=True, verbose_name='Интересы'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='stack',
            field=models.JSONField(blank=True, default=[], null=True, verbose_name='Стек'),
        ),
    ]
