# Generated by Django 5.0.3 on 2024-03-31 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0004_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='profile',
            name='participation_class',
            field=models.IntegerField(default=9, verbose_name='Класс учатия'),
        ),
    ]
