# Generated by Django 5.0.3 on 2024-03-31 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0005_remove_profile_birth_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliableEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Адрес электронной почты')),
            ],
        ),
    ]
