# Generated by Django 5.0.3 on 2024-04-01 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_limitation_main_message'),
        ('authenticate', '0006_avaliableemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.track', verbose_name='Трек'),
        ),
    ]
